CC=g++
CFLAGS=-fopenmp

all: p1 p2 p3_1 p3_2

p1: p1.cpp
	$(CC) $(CFLAGS) p1.cpp -o p1

p2: p2.cpp
	$(CC) $(CFLAGS) p2.cpp -o p2

p3_1: p3_1.cpp
	$(CC) $(CFLAGS) p3_1.cpp -o p3_1

p3_2: p3_2.cpp
	$(CC) $(CFLAGS) p3_2.cpp -o p3_2

clean:
	rm -f p1 p2 p3_1 p3_2
